image: node:9.5.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run build -- --environment SUBDIRECTORY:simply-notes
  artifacts:
    paths:
    - public
  only:
  - master
