name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
